services:
  prometheus:
      image: ttbb/prometheus:mate
      network_mode: "host"
      environment: 
        GLOBAL_SCRAPE_INTERVAL: "15s"
        GLOBAL_SCRAPE_TIMEOUT: "10s"
  grafana:
      image: ttbb/grafana:mate
      network_mode: "host"